In [4]:
#data=pd.read_json('jsonfile',lines=True)

In [5]:
#data.to_csv('data.csv')

# Above codes are for creating csv from json

In [89]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [90]:
data=pd.read_csv('data.csv')

C:\Users\Dell\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (19) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


## Preprocessing

In [155]:
ask_data=data[data['subreddit']=='AskReddit']
#Taking only those data which are from Subreddit AskReddit

In [156]:
ask_data.head(10)

Unnamed: 0  gilded author_flair_css_class  id   link_id  downs  \
14           14       0                    NaN   h  t3_7k903      0   
21           21       0                    NaN   o  t3_7k903      0   
26           26       0                    NaN   t  t3_7k377      0   
50           50       0                    NaN  1h  t3_7k8xe      0   
67           67       0                    NaN  1y  t3_7k8xe      0   
74           74       0                    NaN  25  t3_7k92p      0   
86           86       0                    NaN  2h  t3_7jhu5      0   
104         104       0                    NaN  2z  t3_7k90i      0   
107         107       0                    NaN  32  t3_7k7ff      0   
127         127       0                    NaN  3m  t3_7k7vs      0   

     subreddit          author  score subreddit_id  ...  \
14   AskReddit       [deleted]      1     t5_2qh1i  ...   
21   AskReddit          ermine      1     t5_2qh1i  ...   
26   AskReddit           movzx      3     t5_2qh1i  ...   
50   AskReddit     robrobrobot      5     t5_2qh1i  ...   
67   AskReddit       [deleted]      1     t5_2qh1i  ...   
74   AskReddit       [deleted]      1     t5_2qh1i  ...   
86   AskReddit       [deleted]      1     t5_2qh1i  ...   
104  AskReddit       [deleted]     -1     t5_2qh1i  ...   
107  AskReddit        kenlubin      1     t5_2qh1i  ...   
127  AskReddit  krispykrackers      4     t5_2qh1i  ...   

                                                  body  retrieved_on  \
14                                           [deleted]    1428217153   
21   Ok. Here's what you do. Get some speaker wire ...    1428217153   
26                lol yeah you're right! so hilarious!    1428217153   
50   Yeah, I've contemplated that quite a bit as we...    1428217153   
67                                           [deleted]    1428217153   
74                      Let us plan this one :).......    1428217153   
86                                           [deleted]    1428217153   
104                                          [deleted]    1428217154   
107                                             which?    1428217154   
127  ♥qghy2♥\n\n\nHe's had a lot of reddit love tod...    1428217154   

      parent_id controversiality   name score_hidden  distinguished archived  \
14     t3_7k903                0   t1_h        False            NaN     True   
21     t3_7k903                0   t1_o        False            NaN     True   
26   t1_c06vnj0                0   t1_t        False            NaN     True   
50   t1_c06vwnq                0  t1_1h        False            NaN     True   
67   t1_c06vvz8                0  t1_1y        False            NaN     True   
74   t1_c06vwn9                0  t1_25        False            NaN     True   
86     t3_7jhu5                0  t1_2h        False            NaN     True   
104    t3_7k90i                0  t1_2z        False            NaN     True   
107    t3_7k7ff                0  t1_32        False            NaN     True   
127    t3_7k7vs                0  t1_3m        False            NaN     True   

     created_utc removal_reason  
14    1229580130            NaN  
21    1229580158            NaN  
26    1229580220            NaN  
50    1229580347            NaN  
67    1229580397            NaN  
74    1229580422            NaN  
86    1229580451            NaN  
104   1229580522            NaN  
107   1229580531            NaN  
127   1229580640            NaN  

[10 rows x 23 columns]

In [157]:
ask_data.shape

(62211, 23)

In [158]:
#Removing the contents which
ask_data=ask_data[ask_data['body']!='[deleted]']

In [159]:
ask_data['body']

21        Ok. Here's what you do. Get some speaker wire ...
26                     lol yeah you're right! so hilarious!
50        Yeah, I've contemplated that quite a bit as we...
74                           Let us plan this one :).......
107                                                  which?
                                ...                        
850276    find a rewarding hobby...other than your invet...
850305      I'm already depressed, that just made it worse.
850334                                       `*`applause`*`
850341    You just made me spit take my double ritalin e...
850350    Get her drunk. Have sex with her. Father the c...
Name: body, Length: 55006, dtype: object

In [160]:
#For now, we will just take comments as x and score as our y value
x=ask_data['body']
y=ask_data['score']

In [161]:
x=x.values

### Cleaning the Text

In [162]:
def cleaner(data):
    data1=re.sub('[^a-zA-Z]',' ',data)
    data2=data1.lower()
    data3=data2.strip()
    data4=nltk.word_tokenize(data3)
    data5=[i for i in data4 if i not in set(stopwords.words('english'))]
    data6=[WordNetLemmatizer().lemmatize(i) for i in data5]
    data7=' '.join(data6)
    return data7
cleaner('hi How! are 34 the biggest historian psychology nicer ')

'hi biggest historian psychology nicer'

In [163]:
for k in range(len(x)):
    x[k]=cleaner(x[k])


In [164]:
cleaned_x=x

In [190]:
x=[i.split() for i in x]

In [193]:
len(x)

55006

In [194]:
y.shape

(55006,)

### Using Doc2Vec 


<b>Word2Vec creates sentiments with words where Doc2Vec creates sentiments with sentences.</b>


In [198]:
import gensim
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument

In [201]:
tagged_data=[TaggedDocument(d,[i]) for i,d in enumerate(x)]

In [284]:
len(tagged_data)

55006

In [272]:
model=Doc2Vec(tagged_data,vector_size=20,epochs=100,min_count=0)

In [313]:
model.corpus_count

55006

In [318]:
o_model=model.docvecs.vectors_docs

In [321]:
o_model.shape

(55006, 20)

In [337]:
model.docvecs.vectors_docs.shape

(55006, 20)

In [320]:
y.shape

(55006,)

## Train Test Split

In [325]:
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte=train_test_split(o_model,y,test_size=0.2)

## Trying LinearReg

In [126]:
from sklearn.linear_model import ElasticNet

In [323]:
elr=ElasticNet()

In [327]:
elr.fit(xtr,ytr)

ElasticNet()

In [328]:
y_pred=elr.predict(xte)

In [329]:
y_pred

array([5.109148 , 4.817952 , 4.7380123, ..., 4.7362304, 4.7203574,
       4.8340774], dtype=float32)

In [330]:
yte

321447     3
185329     1
360019     3
657887     4
626714     2
          ..
734204     2
802238    49
695792     9
556959     2
219327     5
Name: score, Length: 11002, dtype: int64

In [332]:
from sklearn.metrics import mean_squared_error,r2_score
print(np.sqrt(mean_squared_error(yte,y_pred)))
print(np.sqrt(r2_score(yte,y_pred)))


11.041633154600301
0.04961057411415197


## Trying NN 

### NN Preprocessing

In [28]:
import tensorflow 
from tensorflow import keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences


In [29]:
tk=Tokenizer(num_words=10000,oov_token='OOV')
tk.fit_on_texts(x)

In [32]:
seq=tk.texts_to_sequences(x)

In [45]:
padded_seq=keras.preprocessing.sequence.pad_sequences(seq,maxlen=100)

In [52]:
max_len=max([len(i.split()) for i in x])
vocab_size=len(tk.word_index)+1
print(max_len,vocab_size)

860 45327


### NN Modeling

In [58]:
model=keras.models.Sequential()
model.add(keras.layers.Embedding(input_dim=vocab_size,output_dim=50,input_length=max_len))
model.add(keras.layers.Bidirectional(keras.layers.LSTM(50)))
model.add(keras.layers.Dense(50))
model.add(keras.layers.Dense(50))
model.add(keras.layers.Dense(1))


In [59]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 860, 50)           2266350   
_________________________________________________________________
bidirectional_1 (Bidirection (None, 100)               40400     
_________________________________________________________________
dense_3 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_4 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 51        
Total params: 2,314,401
Trainable params: 2,314,401
Non-trainable params: 0
_________________________________________________________________


In [60]:
model.compile(loss='mean_squared_error',optimizer='adam',metrics='accuracy')

In [63]:
hist=model.fit(padded_seq,y,batch_size=32,epochs=10,validation_split=0.3)

Epoch 1/10
1204/1204 [==============================] - 113s 88ms/step - loss: 162.3740 - accuracy: 0.3001 - val_loss: 127.8762 - val_accuracy: 0.3443
Epoch 2/10
1203/1204 [============================>.] - ETA: 0s - loss: 199.5233 - accuracy: 0.3100

KeyboardInterrupt: 

### Using TFIDF

In [50]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
x_vec=tfidf.fit_transform(x)

### Using Word2Vec

In [79]:
import gensim

In [81]:
from gensim.models import Word2Vec
qq=Word2Vec(x)

## Creating the model

In [54]:
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte=train_test_split(x_vec,y,test_size=0.3,random_state=12)

In [55]:
print(xtr.shape,ytr.shape,xte.shape,yte.shape)

(38504, 45301) (38504,) (16502, 45301) (16502,)


### ExtraTreesRegressor

In [125]:
from sklearn.ensemble import ExtraTreesRegressor
etr=ExtraTreesRegressor(n_estimators=100,max_depth=5)

In [126]:
etr.fit(xtr,ytr)

ExtraTreesRegressor(max_depth=5)

In [127]:
y_bar=etr.predict(xte)

In [141]:
yte=yte.values

In [148]:
yte[:20]

array([ 2,  2,  3,  6,  3,  4,  6,  3,  2,  1,  1,  3, 64,  6,  1,  2,  2,
        4,  1,  0], dtype=int64)

In [152]:
y_bar[:20]

array([4.72844201, 4.72844201, 4.72844201, 4.72844201, 4.72844201,
       4.72844201, 4.72844201, 4.72844201, 4.72844201, 4.72844201,
       4.72844201, 4.72844201, 4.72844201, 4.72844201, 4.72844201,
       4.72844201, 4.72844201, 4.72844201, 4.72844201, 4.72844201])

### LinearRegression

In [56]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(xtr,ytr)

LinearRegression()

In [58]:
y_bar=lr.predict(xte)

In [60]:
yte[:20]

448520     2
649761     2
272008     3
316804     6
313375     3
155028     4
146751     6
527913     3
521179     2
250433     1
281615     1
227690     3
65602     64
169095     6
93537      1
485018     2
836914     2
701631     4
597426     1
507722     0
Name: score, dtype: int64

In [61]:
y_bar[:20]

array([  5.73330151,  -2.05523801,   5.15453645,  41.98346639,
       -23.09150755,   1.29575738,   0.70849176,   7.34936021,
        -2.73965296,   5.66951156,  -6.99157028,  -2.77485703,
        56.59480901, -20.27972976, -12.69662798, -53.94254226,
        18.86449952,   6.43612577, -18.05670591,   5.31680484])